### ISSUE TITLE
can we use graphQL??? 

### ISSUE THREAD

**Issue by morgancollado** [morgancollado/ntxasn_api#4]
idk can we?

**Comment by sofie-c** [comment]
Result from spike: [here's](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-ruby-on-rails-graphql-api) how we can set up GQL for the app. 

We'll want to be extra mindful of authn/authz for GQL. Here are some helpful docs for that:
 - [Authn](https://www.howtographql.com/graphql-ruby/4-authentication/)
 - [Authz](https://graphql-ruby.org/authorization/authorization)
 
In general, we'll be referencing the graphql-ruby [docs](https://graphql-ruby.org/) a bunch too.
